when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
app:
  resource: ../../src/Presentation/Http/App/Controller/
  type: attribute

kernel:
  resource: ../../src/Kernel.php
  type: attribute